### ISSUE TITLE
why it is so slowly to open menu? 

### ISSUE THREAD

**Issue by energygreek** [onuronsekiz/obamenu#1]
i need to wait almost 20s to see my menu.  is it because of python ?

**Comment by onuronsekiz** [comment]
I don't think it is related with python, probably code can't find one of your programs proper icon. Code can't find it and search through all icon folders. I had tested this issue before releasing code to github and usually it would take maximum 1-2 second to search all folders even if it couldn't find any matching icon. Try to find your missing icon program or reduce your icon packs. This code has been written for minimal approach of window managers and icon packs so I didn't consider anyone would have a lot of icon packs and programs that don't have proper icons. 
Please, if you could provide programs and icon packs you have installed I can help you better.
