### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by opqriu** [onuronsekiz/obamenu#3]
~$ ./obamenu.py 

./obamenu.py: line 7: syntax error near unexpected token `newline'
./obamenu.py: line 7: `<!DOCTYPE html>'

~$

Failed.
I'm sad.
I am use debian 10.
Help me?

**Comment by onuronsekiz** [comment]
This is not a python or code error, it is shell error. Probably your bash, fish, etc giving this error.
Could you please try to run command `python3 obamenu.py` and inform the result?
If you have set python3 over python2 then typing `python obamenu.py` should suffice too.
You may also have to install python latest version if yours is too old.

Please re-download the code, a crucial error is fixed if no icon is found.
Also try with revising line35 to `selected_theme = "gnome"`.

**Comment by opqriu** [comment]
0.
Debian 10 minimal install & openbox install

1.
obamenu.py download.

2.
Terminal
~$ chmod +x obamenu.py
~$ chmod 754 obamenu.py

3.
menu.xml add
<menu execute="~/.path/to/obamenu.py" id="My Menu" label="Applications" />

4.
 I do get the "Applications" submenu, but just passing the mouse over that brings an error box with the sayings:

"invalid output from pipe-menu "obamenu""

And,
in Terminal

~$ python3 obamenu.py 
  File "obamenu.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

~$ python obamenu.py 
  File "obamenu.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

5.
If the Python version is the problem, I'll be waiting for Debian 11 Bullseye to release.
Thank you.

**Comment by onuronsekiz** [comment]
I have checked with debian-gnome livecd, installed openbox. (under qemu)
Done the requirements (copying, installing, revising code, etc) for ob.
Logout from gnome, login to openbox, tried obamenu.py and everything works.

I will install debian with minimal iso and check with it. May edit this post later.

**Comment by onuronsekiz** [comment]
Apparently there is something wrong with your installation.
Here are the steps I have done, it worked without any problem.

1. Install Debian10 standard.
2. After installation completed and login;
```
    su
    apt update
    apt install lightdm
    apt install openbox obconf firefox-esr mousepad pcmanfm
    exit
    mkdir ~/.config/openbox
    cp /etc/xdg/openbox/* ~/.config/openbox/
```
3. Reboot
4. Download obamenu.py
5. Revise line35 to `selected_theme="gnome"`
6. `chmod +x obamenu.py`
7. Edit menu.xml and add line `<menu id="pipe1" label="Obamenu" execute="~/.config/openbox/obamenu.py"/>`
8. Restart openbox.

No problem has occured on either installing or working.
I don't think the python code has the bug for that particular error.
I can only suggest you to check your installation. Closing the issue.
Best regards.

![2021-04-05_00-58](https://user-images.githubusercontent.com/76511536/113522587-797ac500-95aa-11eb-951d-ae8262cd5446.png)

**Comment by opqriu** [comment]
I found a mistake.  
35 Line could not be corrected properly. 
I didn't know what this meant.  
Now I am successful and happy.  
Thank you for your consideration.

**Comment by onuronsekiz** [comment]
So obamenu worked for you, I am glad.
I will revise installation steps in readme to state this issue.
