### ISSUE TITLE
"Education" menu does not appear

### ISSUE THREAD

**Issue by fredbird67** [onuronsekiz/obamenu#4]
First of all, thank you for an updated Obamenu that shows installed applications alphabetically.  However, I have discovered a problem.

I just discovered that any applications that, in /usr/share/applications/, are categorized as "Education" do not show up at all, nor does the "Education" category itself.

I am working on an update to a distro I have created, called F3OS, that has built-in web filtering and has the Xiphos Bible study program pre-installed, among other things people would likely use on a frequent basis -- and Xiphos is categorized as "Education".  This is a lite edition of my distro that uses Openbox (the main edition uses Xfce and therefore doesn't have this problem).

Even worse, I have three scripts that 1) let one change DNS filtering providers, 2) install packs of software that might be of interest to users, listed by category, and, 3) for schools as well as for homeschooling parents, install educational software -- NONE of which will show up in your script the way it is right now.

**Comment by fredbird67** [comment]
PS -- My distro project is based on Debian Stable (currently Bookworm), if this is information you need.

**Comment by onuronsekiz** [comment]
You can add whatever group you need. It is in line #34, you can add "Education" as an additional group.

**Comment by fredbird67** [comment]
Oh, OK.  Thank you -- I'll edit that after I get home later today after my SAR (Sons of the American Revolution) meeting this afternoon.  Thought I was gonna have to possibly replace Openbox with IceWM over this, but now I won't have to.  Thank you very much!  And yes, you may consider this issue closed.
